### ISSUE TITLE
Game is too grindy

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#280]
It's literally join, grind, get some basic stuff, do some quests, go to seashell village, grind for a few months, fight ten eyed one, die, grind a few more weeks, fight ten eyed one. You grind for the majority of your time playing and the whole time ur dying and waiting for the respawn timer.

**Comment by Suvanth-Erranki** [comment]
It's not grindy unless you are trying to get the better items. You can just get staff of life or thorned bow (which doesn't take that long) and PVP players. Also this is subjective, because you described how you think the game is intended to be played, which could be different from what other players think and what Maitian thinks.

**Comment by maitian352** [comment]
It's because theres not enough content/quests yet.

**Comment by definitely-nobody-is-here** [comment]
its still grindy
i have to write the entire game to play it
where server
